from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('programming', views.programming),
    path('layouting', views.layouting),
    path('ratings', views.ratings),
    path('platform', views.platform),
    path('authors', views.authors),

    path('condition', views.condition),
    path('politics', views.politics),

    path('c_main', views.c_main),
    path('c-lesson-1', views.clesson1),
    path('c-lesson-2', views.clesson2),
    path('c-lesson-3', views.clesson3),
    path('c-lesson-4', views.clesson4),
    path('c-lesson-5', views.clesson5),
    path('c-lesson-6', views.clesson6),
    path('c-lesson-7', views.clesson7),
    path('c-lesson-8', views.clesson8),

    path('c_sharp_main', views.c_sharp_main),
    path('c-sharp-lesson-1', views.csharplesson1),
    path('c-sharp-lesson-2', views.csharplesson2),
    path('c-sharp-lesson-3', views.csharplesson3),
    path('c-sharp-lesson-4', views.csharplesson4),
    path('c-sharp-lesson-5', views.csharplesson5),
    path('c-sharp-lesson-6', views.csharplesson6),
    path('c-sharp-lesson-7', views.csharplesson7),
    path('c-sharp-lesson-8', views.csharplesson8),
    path('c-sharp-lesson-9', views.csharplesson9),
    path('c-sharp-lesson-10', views.csharplesson10),

    path('css_s_main', views.css_s_main),
    path('css-lesson-1', views.css_slesson1),
    path('css-lesson-2', views.css_slesson2),
    path('css-lesson-3', views.css_slesson3),
    path('css-lesson-4', views.css_slesson4),
    path('css-lesson-5', views.css_slesson5),
    path('css-lesson-6', views.css_slesson6),
    path('css-lesson-7', views.css_slesson7),
    path('css-lesson-8', views.css_slesson8),

    path('go_main', views.go_main),

    path('java_main', views.java_main),
    path('java-lesson-1', views.javalesson1),
    path('java-lesson-2', views.javalesson2),
    path('java-lesson-3', views.javalesson3),
    path('java-lesson-4', views.javalesson4),
    path('java-lesson-5', views.javalesson5),
    path('java-lesson-6', views.javalesson6),

    path('javascript_main', views.javascript_main),
    path('javascript-lesson-1', views.javascriptlesson1),
    path('javascript-lesson-2', views.javascriptlesson2),
    path('javascript-lesson-3', views.javascriptlesson3),
    path('javascript-lesson-4', views.javascriptlesson4),
    path('javascript-lesson-5', views.javascriptlesson5),
    path('javascript-lesson-6', views.javascriptlesson6),

    path('php_main', views.php_main),
    path('php-lesson-1', views.phplesson1),
    path('php-lesson-2', views.phplesson2),
    path('php-lesson-3', views.phplesson3),
    path('php-lesson-4', views.phplesson4),
    path('php-lesson-5', views.phplesson5),
    path('php-lesson-6', views.phplesson6),
    path('php-lesson-7', views.phplesson7),
    path('php-lesson-8', views.phplesson8),
    path('php-lesson-9', views.phplesson9),

    path('python_main', views.python_main),
    path('python-lesson-1', views.pythonlesson1),
    path('python-lesson-2', views.pythonlesson2),
    path('python-lesson-3', views.pythonlesson3),
    path('python-lesson-4', views.pythonlesson4),
    path('python-lesson-5', views.pythonlesson5),
    path('python-lesson-6', views.pythonlesson6),
    path('python-lesson-7', views.pythonlesson7),
    path('python-lesson-8', views.pythonlesson8),

    path('racket_main', views.racket_main),

    path('ruby_main', views.ruby_main),
    path('ruby-lesson-1', views.rubylesson1),
    path('ruby-lesson-2', views.rubylesson2),
    path('ruby-lesson-3', views.rubylesson3),
    path('ruby-lesson-4', views.rubylesson4),
    path('ruby-lesson-5', views.rubylesson5),
    path('ruby-lesson-6', views.rubylesson6),
    path('ruby-lesson-7', views.rubylesson7),
    path('ruby-lesson-8', views.rubylesson8),
    path('ruby-lesson-9', views.rubylesson9),

    path('typescript_main', views.typescript_main),

    path('html_main', views.html_main),
    path('html-lesson-1', views.htmllesson1),
    path('html-lesson-2', views.htmllesson2),
    path('html-lesson-3', views.htmllesson3),
    path('html-lesson-4', views.htmllesson4),
    path('html-lesson-5', views.htmllesson5),
    path('html-lesson-6', views.htmllesson6),
    path('html-lesson-7', views.htmllesson7),

    path('register', views.RegisterView.as_view(), name='register'),
]